# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d1a799a016bd871fb2f6a9d4b7ee824fa69915fe09f33a99f2eef7e3a1aa515035a364437221b7c70be6042cef00bcc621d673428fe1443889ca366741deda

test:
  secret_key_base: c943958d752f390210c971d4122822ce56e006e7d89d84b0f6fe50e408d831a92ea4455100f652c6324a9e1fb5e37fe77a68c8e2ea15cc69c1b6e8f399abab27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
